version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${ARLAS_IAM_HIBERNATE_USER:-pg-user}
      POSTGRES_PASSWORD: ${ARLAS_IAM_HIBERNATE_PASSWORD:-iAMs00perSecrEET}
      POSTGRES_DB: arlas_iam
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ${ARLAS_IAM_DATADIR:-/tmp}:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: tech@gisaia.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "8080:80"
#    volumes:
#    # on your local host: chmod -R 777 /home/user/projects/postgis/pgadmin
#    #- /home/user/projects/postgis/pgadmin/servers.json:/pgadmin4/servers.json
#    #- /home/user/projects/postgis/pgadmin/data:/var/lib/pgadmin
#      - ${PGA_CONFIG}:/pgadmin4/servers.json
#      - ${PGA_DATADIR}:/var/lib/pgadmin
#
  arlas-iam-server:
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only}
    image: docker.cloudsmith.io/gisaia/private/arlas-iam-server:${ARLAS_IAM_SERVER_VERSION:-latest}
    container_name: arlas-iam-server
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.expand_keys: true
    environment:
      - ARLAS_IAM_HOST="${ARLAS_IAM_HOST:-localhost}"
      - ARLAS_IAM_PORT="${ARLAS_IAM_PORT:-9997}"
      - ARLAS_IAM_PREFIX="${ARLAS_IAM_PREFIX:-/arlas_iam_server}"
      - ARLAS_IAM_APP_PATH="${ARLAS_IAM_APP_PATH:-/}"
      - ARLAS_ANONYMOUS_VALUE="${ARLAS_ANONYMOUS_VALUE:-anonymous}"
      - ARLAS_AUTH_PUBLIC_URIS=${ARLAS_AUTH_PUBLIC_URIS:-swagger,swagger.*,session:POST,session/.*:PUT,users:POST,users/.*:POST}
      - ARLAS_IAM_VERIFY_EMAIL="${ARLAS_IAM_VERIFY_EMAIL:-true}"
      - ARLAS_IAM_PRIVATE_ORG="${ARLAS_IAM_PRIVATE_ORG:-false}"
      - ARLAS_IAM_HIBERNATE_URL="${ARLAS_IAM_HIBERNATE_URL:-jdbc:postgresql://db:5432/arlas_iam}"
      - ARLAS_IAM_HIBERNATE_USER="${ARLAS_IAM_HIBERNATE_USER:-pg-user}"
      - ARLAS_IAM_HIBERNATE_PASSWORD="${ARLAS_IAM_HIBERNATE_PASSWORD:-iAMs00perSecrEET}"
      - ARLAS_IAM_HIBERNATE_DRIVER="${ARLAS_IAM_HIBERNATE_DRIVER:-org.postgresql.Driver}"
      - ARLAS_IAM_HIBERNATE_DIALECT="${ARLAS_IAM_HIBERNATE_DIALECT:-org.hibernate.dialect.PostgreSQLDialect}"
      - ARLAS_SMTP_ACTIVATED="${ARLAS_SMTP_ACTIVATED:-false}"
      - ARLAS_SMTP_HOST="${ARLAS_SMTP_HOST:-}"
      - ARLAS_SMTP_PORT="${ARLAS_SMTP_PORT:-25}"
      - ARLAS_SMTP_USERNAME="${ARLAS_SMTP_USERNAME:-}"
      - ARLAS_SMTP_PASSWORD="${ARLAS_SMTP_PASSWORD:-}"
      - ARLAS_SMTP_FROM="${ARLAS_SMTP_FROM:-}"
      - ARLAS_SMTP_VERIFY_LINK="${ARLAS_SMTP_VERIFY_LINK:-/users/%s/verify/%s}"
      - ARLAS_SMTP_RESET_LINK="${ARLAS_SMTP_RESET_LINK:-/users/%s/reset/%s}"
      - ARLAS_CACHE_TIMEOUT="${ARLAS_CACHE_TIMEOUT:-5}"
      - ARLAS_IAM_LOGGING_LEVEL="${ARLAS_IAM_LOGGING_LEVEL:-INFO}"
      - ARLAS_IAM_LOGGING_CONSOLE_LEVEL="${ARLAS_IAM_LOGGING_CONSOLE_LEVEL:-INFO}"
      - ARLAS_SERVER_URL="${ARLAS_SERVER_URL:-http://arlas-server:9999/arlas/}"
      - ARLAS_ACCESS_TOKEN_TTL="${ARLAS_ACCESS_TOKEN_TTL:-600000}"
    #      - ELASTIC_APM_LOG_ECS_REFORMATTING=OVERRIDE
    #      - ELASTIC_APM_LOG_ECS_FORMATTER_ALLOW_LIST=*
    #      - ELASTIC_APM_APPLICATION_PACKAGES=io.arlas
    #      - ELASTIC_APM_ENVIRONMENT=dev.cloud.arlas.io
    #      - ELASTIC_APM_TRANSACTION_IGNORE_USER_AGENTS=GoogleHC/*, kube-probe/*, curl*, GoogleStackdriverMonitoring*
    #      - ELASTIC_APM_SECRET_TOKEN=YDaIBr3Pfm9k69xuZk
    #      - ELASTIC_APM_SERVER_URLS=https://1b48d14497994c518cf959079ddcfd6d.apm.europe-west1.gcp.cloud.es.io
    #      - ELASTIC_APM_SERVICE_NAME=arlas-server
    #      - ELASTIC_APM_USE_JAXRS_PATH_AS_TRANSACTION_NAME=true
    #      - JDK_JAVA_OPTIONS=-javaagent:/opt/app/elastic-apm-agent.jar
    ports:
      - "9997:9997"

  arlas-server:
    image: gisaia/arlas-server:24.0.2-SNAPSHOT
    container_name: arlas-server
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.expand_keys: true
    environment:
    - ARLAS_ELASTIC_NODES=${ARLAS_ELASTIC_NODES:-690a605d3db34f749f1c7bb57e08e45f.europe-west1.gcp.cloud.es.io:9243}
    - ARLAS_ELASTIC_ENABLE_SSL="${ARLAS_ELASTIC_ENABLE_SSL:-true}"
    - ARLAS_ELASTIC_CREDENTIALS="${ARLAS_ELASTIC_CREDENTIALS:-elastic:ZR45O3x5sUJWJJ6PxsB8dkPQ}"
    - ARLAS_PREFIX="${ARLAS_PREFIX:-/arlas}"
    - ARLAS_APP_PATH="${ARLAS_APP_PATH:-/}"
    - ARLAS_BASE_URI="${ARLAS_BASE_URI:-http://arlas-server:9999/arlas/}"
    - ARLAS_SERVICE_WFS_ENABLE="${ARLAS_SERVICE_WFS_ENABLE:-false}"
    - ARLAS_INSPIRE_ENABLED="${ARLAS_INSPIRE_ENABLED:-false}"
    - ARLAS_SERVICE_CSW_ENABLE="${ARLAS_SERVICE_CSW_ENABLE:-false}"
    - ARLAS_SERVICE_RASTER_TILES_ENABLE="${ARLAS_SERVICE_RASTER_TILES_ENABLE:-false}"
    - ARLAS_AUTH_POLICY_CLASS="${ARLAS_AUTH_POLICY_CLASS:-io.arlas.filter.impl.HTTPPolicyEnforcer}"
    - ARLAS_AUTH_PERMISSION_URL="${ARLAS_AUTH_PERMISSION_URL:-http://arlas-iam-server:9997/arlas_iam_server/permissions}"
    - ARLAS_CORS_ENABLED="${ARLAS_CORS_ENABLED:-false}"
    - ARLAS_AUTH_CERT_URL="${ARLAS_AUTH_CERT_URL}"
    - ARLAS_CACHE_FACTORY_CLASS="${ARLAS_CACHE_FACTORY_CLASS:-io.arlas.server.core.impl.cache.HazelcastCacheFactory}"
    - ARLAS_CACHE_TIMEOUT="${ARLAS_CACHE_TIMEOUT:-5}"
    - ARLAS_LOGGING_LEVEL=DEBUG
    - ARLAS_LOGGING_CONSOLE_LEVEL=DEBUG
    - ARLAS_ELASTIC_INDEX=.iamtest_arlas
    #      - ELASTIC_APM_LOG_ECS_REFORMATTING=OVERRIDE
    #      - ELASTIC_APM_LOG_ECS_FORMATTER_ALLOW_LIST=*
    #      - ELASTIC_APM_APPLICATION_PACKAGES=io.arlas
    #      - ELASTIC_APM_ENVIRONMENT=dev.cloud.arlas.io
    #      - ELASTIC_APM_TRANSACTION_IGNORE_USER_AGENTS=GoogleHC/*, kube-probe/*, curl*, GoogleStackdriverMonitoring*
    #      - ELASTIC_APM_SECRET_TOKEN=YDaIBr3Pfm9k69xuZk
    #      - ELASTIC_APM_SERVER_URLS=https://1b48d14497994c518cf959079ddcfd6d.apm.europe-west1.gcp.cloud.es.io
    #      - ELASTIC_APM_SERVICE_NAME=arlas-server
    #      - ELASTIC_APM_USE_JAXRS_PATH_AS_TRANSACTION_NAME=true
    #      - JDK_JAVA_OPTIONS=-javaagent:/opt/app/elastic-apm-agent.jar
    ports:
      - "9999:9999"
    volumes:
      - ${ARLAS_AUTH_LOCAL_CERT_FILE:-/tmp}:${ARLAS_AUTH_CERT_FILE:-/opt/app/arlas.pem}:ro
