ARG TAG=latest
FROM gisaia/arlas-tagger:$TAG

WORKDIR /opt/app

# add auth configuration fragment to server configuration
ADD conf/auth-fragment.yaml /opt/app/auth-fragment.yaml
RUN cat /opt/app/auth-fragment.yaml >> /opt/app/configuration.yaml

COPY arlas-iam-filter/target/arlas-iam-filter-*.jar /opt/app/arlas-iam-filter.jar
ENV CP="./arlas-iam-filter.jar:./arlas-tagger.jar"
ENV ARLAS_AUTH_TYPE="auth"
