ARG TAG=latest
FROM gisaia/arlas-persistence-server:$TAG

WORKDIR /opt/app

# add auth configuration fragment to server configuration
ADD conf/auth-fragment.yaml /opt/app/auth-fragment.yaml
RUN cat /opt/app/auth-fragment.yaml >> /opt/app/configuration.yaml

COPY arlas-ums-filter/target/arlas-ums-filter-*.jar /opt/app/arlas-ums-filter.jar
ENV CP="./arlas-ums-filter.jar:./arlas-persistence-server.jar"
ENV ARLAS_AUTH_TYPE="auth"
