version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${ARLAS_UMS_HIBERNATE_USER:-pg-user}
      POSTGRES_PASSWORD: ${ARLAS_UMS_HIBERNATE_PASSWORD:-iAMs00perSecrEET}
      POSTGRES_DB: arlas_ums
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ${ARLAS_UMS_DATADIR:-/tmp}:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: tech@gisaia.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "8080:80"
#    volumes:
#    # on your local host: chmod -R 777 /home/user/projects/postgis/pgadmin
#    #- /home/user/projects/postgis/pgadmin/servers.json:/pgadmin4/servers.json
#    #- /home/user/projects/postgis/pgadmin/data:/var/lib/pgadmin
#      - ${PGA_CONFIG}:/pgadmin4/servers.json
#      - ${PGA_DATADIR}:/var/lib/pgadmin

  arlas-auth-server:
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-auth-package-only}
    image: gisaia/arlas-auth-server:${ARLAS_UMS_SERVER_VERSION:-latest}
    container_name: arlas-auth-server
    environment:
      - ARLAS_UMS_HOST="${ARLAS_UMS_HOST:-localhost}"
      - ARLAS_UMS_PORT="${ARLAS_UMS_PORT:-9997}"
      - ARLAS_UMS_PREFIX="${ARLAS_UMS_PREFIX:-/arlas_auth_server}"
      - ARLAS_UMS_APP_PATH="${ARLAS_UMS_APP_PATH:-/}"
      - ARLAS_ANONYMOUS_VALUE="${ARLAS_ANONYMOUS_VALUE:-anonymous}"
      - ARLAS_UMS_PUBLIC_URIS=${ARLAS_UMS_PUBLIC_URIS:-swagger,swagger.*,permissions:GET}
      - ARLAS_UMS_VERIFY_EMAIL="${ARLAS_UMS_VERIFY_EMAIL:-true}"
      - ARLAS_UMS_HIBERNATE_URL="${ARLAS_UMS_HIBERNATE_URL:-jdbc:postgresql://db:5432/arlas_ums}"
      - ARLAS_UMS_HIBERNATE_USER="${ARLAS_UMS_HIBERNATE_USER:-pg-user}"
      - ARLAS_UMS_HIBERNATE_PASSWORD="${ARLAS_UMS_HIBERNATE_PASSWORD:-iAMs00perSecrEET}"
      - ARLAS_UMS_HIBERNATE_DRIVER="${ARLAS_UMS_HIBERNATE_DRIVER:-org.postgresql.Driver}"
      - ARLAS_UMS_HIBERNATE_DIALECT="${ARLAS_UMS_HIBERNATE_DIALECT:-org.hibernate.dialect.PostgreSQLDialect}"
    ports:
      - "9990:9997"
    command: ["/opt/app/start.sh"]

  arlas-idp-server:
    build:
      context: ../..
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-idp-package-only}
    image: gisaia/arlas-idp-server:${ARLAS_UMS_SERVER_VERSION:-latest}
    container_name: arlas-idp-server
    environment:
      - ARLAS_UMS_HOST="${ARLAS_UMS_HOST:-localhost}"
      - ARLAS_UMS_PORT="${ARLAS_UMS_PORT:-9997}"
      - ARLAS_UMS_PREFIX="${ARLAS_UMS_PREFIX:-/arlas_idp_server}"
      - ARLAS_UMS_APP_PATH="${ARLAS_UMS_APP_PATH:-/}"
      - ARLAS_ANONYMOUS_VALUE="${ARLAS_ANONYMOUS_VALUE:-anonymous}"
      - ARLAS_UMS_PUBLIC_URIS=${ARLAS_UMS_PUBLIC_URIS:-swagger,swagger.*,session:POST,users:POST,users/.*:POST}
      - ARLAS_UMS_VERIFY_EMAIL="${ARLAS_UMS_VERIFY_EMAIL:-true}"
      - ARLAS_UMS_HIBERNATE_URL="${ARLAS_UMS_HIBERNATE_URL:-jdbc:postgresql://db:5432/arlas_ums}"
      - ARLAS_UMS_HIBERNATE_USER="${ARLAS_UMS_HIBERNATE_USER:-pg-user}"
      - ARLAS_UMS_HIBERNATE_PASSWORD="${ARLAS_UMS_HIBERNATE_PASSWORD:-iAMs00perSecrEET}"
      - ARLAS_UMS_HIBERNATE_DRIVER="${ARLAS_UMS_HIBERNATE_DRIVER:-org.postgresql.Driver}"
      - ARLAS_UMS_HIBERNATE_DIALECT="${ARLAS_UMS_HIBERNATE_DIALECT:-org.hibernate.dialect.PostgreSQLDialect}"
      - ARLAS_SMTP_ACTIVATED="${ARLAS_SMTP_ACTIVATED:-false}"
      - ARLAS_SMTP_HOST="${ARLAS_SMTP_HOST:-}"
      - ARLAS_SMTP_PORT="${ARLAS_SMTP_PORT:-25}"
      - ARLAS_SMTP_USERNAME="${ARLAS_SMTP_USERNAME:-}"
      - ARLAS_SMTP_PASSWORD="${ARLAS_SMTP_PASSWORD:-}"
      - ARLAS_SMTP_FROM="${ARLAS_SMTP_FROM:-}"
      - ARLAS_SMTP_VERIFY_LINK="${ARLAS_SMTP_VERIFY_LINK:-/users/%s/verify/%s}"
    ports:
      - "9991:9997"
    command: ["/opt/app/start.sh"]
